[project]
name = "aegis-frontend"
version = "0.1.0"
description = "Streamlit Frontend for Enhanced Multi-Agent Compliance System"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.28.0",
    "requests>=2.31.0",
    "pandas>=2.1.0",
    "plotly>=5.17.0",
]